---
title: "Observational study NOG/COG Results"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = '../')
knitr::opts_chunk$set(echo = F, include = T, message = F, warning = F, cache = T, cache.lazy = FALSE)
```

```{r libraries}
library(tximport)
library(ggplot2)
library(ggrepel)
library(readr)
library(DESeq2)
library(dplyr)
library(ggthemes)
library(vegan)
library(kableExtra)
```

```{r tximport_og}
txi_og <- read_tsv("outputs/tx2gene/eggnog_tx2gene_og.tsv")
txi_og <- filter(txi_og, grepl("@", GENEID))
obs <- read_csv("inputs/tximport_samples/observational_samples.csv")
# obs_counts_og <- tximport(files = obs$filename, type = "salmon", tx2gene = txi_og)
# saveRDS(obs_counts_og, "outputs/diff_abund/observational_species/tximport_og.RDS")
obs_counts_og <- readRDS("outputs/diff_abund/observational_species/tximport_og.RDS")
```

```{r export_counts}
obs_counts_raw <- obs_counts_og$counts
colnames(obs_counts_raw) <- obs$sample
obs_counts_raw <- as.data.frame(obs_counts_raw)
obs_counts_raw$ortholog <- rownames(obs_counts_raw)
write_tsv(obs_counts_raw, "outputs/ortholog_counts/obs_og_counts_raw.tsv")
```


```{r diff_model_og}
#ddsTxi_og <- DESeqDataSetFromTximport(obs_counts_og,
#                                       colData = obs,
#                                       design = ~ status + diet_type + physiology)
# dds_og <- DESeq(ddsTxi_og)
# saveRDS(dds_og, "outputs/diff_abund/observational_species/dds_og.RDS")
dds_og <- readRDS("outputs/diff_abund/observational_species/dds_og.RDS")

#resultsNames(dds_og) # lists the coefficients
```

```{r norm_counts}
dds_og <- estimateSizeFactors(dds_og)
dds_og_counts <- counts(dds_og, normalized=TRUE)
colnames(dds_og_counts) <- colData(dds_og)$sample
dds_og_counts <- as.data.frame(dds_og_counts)
dds_og_counts$KO <- rownames(dds_og_counts)
write_tsv(dds_og_counts, "outputs/ortholog_counts/obs_og_counts_norm.tsv")
```

```{r pca_og}
vsd <- vst(dds_og)
pca_data <- plotPCA(vsd, intgroup = c("status", "species"), returnData=TRUE)
percentVar <- round(100 * attr(pca_data, "percentVar"))


ggplot(pca_data, aes(PC1, PC2, shape=status, color=species)) + 
  theme_minimal() +
  geom_point(size=3) +
  geom_text_repel(aes(label = species)) +
  #geom_text_repel(aes(label = day)) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) +
  ggtitle("PCA plot of NOG/COG orthologs in observational study") +
  scale_color_tableau(palette = "Tableau 20")
```

```{r permanova}
vsd_assay <- t(assay(vsd))
rownames(vsd_assay) <- colData(vsd)$sample
veg_dist <- vegdist(vsd_assay, "bray")

obs <- obs[match(rownames(vsd_assay), obs$sample), ] # sort info by colnames
obs$species <- as.factor(obs$species)              # set factors for model
obs$status <- as.factor(obs$status)
obs$diet_type <- as.factor(obs$diet_type)
obs$physiology <- as.factor(obs$physiology)              # set factors for model
obs$dom_type <- as.factor(obs$dom_type)

perm <- adonis(veg_dist ~ dom_type + diet_type + physiology + status + species, 
               data = obs, 
               permutations = 10000)

write.table(perm$aov.tab, "outputs/permanova/observational_og_permanova.tsv", quote = F)
kable(perm$aov.tab) %>% kable_styling()
```

## Wild vs. domesticated -- Differential abundance


```{r og_diet_res}
res <- results(dds_og, name="status_wild_vs_domestic")
res <- res[order(res$pvalue), ]

res_sig <- res %>%
  as.data.frame %>%
  mutate(ortholog = rownames(.)) %>%
  filter(grepl("@", ortholog)) %>%
  filter(padj < .05) %>%
  mutate(id = seq(1:nrow(.)))

res_og <- res %>%
  as.data.frame %>%
  mutate(ortholog = rownames(.)) %>%
  filter(grepl("@", ortholog))
```

`r nrow(txi_og)` genes annotated to `r nrow(res_og)` NOG/COG orthologs. `r nrow(res_sig)` were significantly 
differentially abundant between wild and domesticated species.
`r table(res_sig$log2FoldChange < 0)[1]` were more 
abundant in wild species, while `r table(res_sig$log2FoldChange < 0)[2]` were more abundant in the domesticated species.


```{r write_tsvs}
write_tsv(res_sig, "outputs/diff_abund/observational_species/observational_og_sig.tsv")
write_tsv(res_og, "outputs/diff_abund/observational_species/observational_og_all.tsv")
```